### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by varchun**
В тебе є 12 годин, хлопче

### CODE REVIEW

**Comment by nickesc** [comment]
This is a scraper for a weed subscription service's menu -- if there is a real reason for me to take it down, I will. Why are you asking me to remove Nugg Club Scraper? The repo has been removed until I get more information, but will eventually go back up if I don't.

**Comment by varchun** [comment]
It really looks like fishing endpoint that requests real data. Why?

**Comment by nickesc** [comment]
I'm not sure what you mean. I just wrote this for fun to practice scraping HTML and putting together a command-line program. It doesn't even work anymore in its current state, the website it scraped changed its layout. It has a few different backup data sources, so I could still use it as an example of work if they ever changed their web page. The GitHub Pages site is just an archived version of their site from a few months ago, if that's what you're talking about. Unless you have a reason for me not to put it back up, I will be making the repo public again.

**Comment by varchun** [comment]
we see all your errors in our services - this was not the first such situation ) Try to exclude 3rd-party services and make it public again.
Are you a student? If this was only for fun and studing, so everything is good - I can only wish you success. Have a great day, man!

**Comment by nickesc** [comment]
Aah I see -- sorry about that! I am a student, just messing around with what I can do. I'll take a look at the code and remove what I need to. Thanks!

**Pull request closed without merging**
